#!/bin/bash

modular_base_plus_modules () {
    modular_set_ignore sources.d sources/modules/contrib/admin sources/modules/contrib/applications sources/modules/contrib/roles \
        sources/modules/contrib/services sources/modules/contrib/system

    unset MODULAR_BASE_PLUS_MODULES

    MODULAR_BASE_PLUS_MODULES+=("${MODULAR_SMODULES[*]}")
}

modular_base_plus_run_test () {
    modular_base_plus_modules

    local TEST="modular_base_plus_modules"

    if [ "${MODULAR_VERBOSE}" == "1" ] ; then
        ${SECILC} -v $(echo ${MODULAR_BASE_PLUS_MODULES[@]}) \
            -o policy/policy.${VERSION}.${TEST} -f contexts/files/file_contexts.${TEST}
    else
        ${SECILC} $(echo ${MODULAR_BASE_PLUS_MODULES[@]}) \
            -o policy/policy.${VERSION}.${TEST} -f contexts/files/file_contexts.${TEST} 2>/dev/null
    fi

    if [ "$?" -ne 0 ] ; then
        return 192
    fi
}

#EOF
